---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-main
  labels:
    app: web
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
      role: main
  template:
    metadata:
      labels:
        app: web
        role: main
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        imagePullPolicy: Always
        args: [ 'busy=400' ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
        ports:
          - containerPort: 8080
