---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
    name: co-http

---
apiVersion: v1
kind: Service
metadata:
  name: web-preview
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
    name: co-http

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-main
  labels:
    app: web
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
      role: main
  strategy:
    blueGreen: 
      activeService: web
      previewService: web-preview
  template:
    metadata:
      labels:
        app: web
        role: main
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        imagePullPolicy: Always
        args: [ 'busy=400' ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
        ports:
          - containerPort: 8080
