name: Quick Start
on:
  push:
    branches: [main]

jobs:
  quick_start:
    name: Pyenv Quick Start
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.5
          - 3.8.6
          - 3.9.0

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: Cache pyenv versions
      uses: actions/cache@v2.1.1
      id: cached-pyenvs
      with:
        path: .
        key: ${{ runner.os }}-python-${{ matrix.python }}
    - name: Install pyenv versions
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        versions: 3.8.5, 3.8.6, 3.9.0
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        pyenv install -s
        poetry env info
        poetry env use `cat .python-version`
    - name: Cache dependencies
      uses: actions/cache@v2.1.1
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    - name: Run tests
      run: |
        source $HOME/.poetry/env
        poetry run pytest
