name: Release
on:
  release:
    types: [published]
jobs:
  release:
    if: ${{ github.repository == 'opsani/servox' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.1.3
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install and configure Poetry
      run: |
        pip install poetry==1.1.*
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: poetry run pytest tests
    - name: Build artifacts
      run: poetry build
    - name: Publish to PyPI
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
